#!/usr/bin/env python3
"""Guarda de mutacao — prova que os guardas que ja existem TEM testes que os vigiam.

PORQUE ISTO EXISTE. Nesta base de codigo, DUAS vezes documentadas, um fix vivo ficou com testes
mortos: a suite passava na mesma com o fix REMOVIDO. O caso mais recente passou 5/5 com o portao
de cobertura arrancado — o revert que o teste apanhava vinha de OUTRA verificacao com o MESMO
codigo de erro. Um revert com o codigo certo nao prova que a verificacao certa disparou.

NAO E UMA FERRAMENTA DE MUTACAO GENERICA, de proposito. E uma lista FIXA e VERSIONADA de mutantes,
cada um emparelhado com o teste nomeado que TEM de o apanhar. Corre em segundos, nao precisa de
framework, e falha de forma legivel: diz que guarda ficou sem vigia.

O CONTRATO: aplicar o mutante -> o teste nomeado tem de ficar VERMELHO. Se ficar verde, o guarda
esta desprotegido e o CI para. Adicionar um guarda de seguranca ao protocolo implica adicionar a
sua linha aqui.
"""
import subprocess, sys, shutil, os, tempfile

M = [
 dict(nome="portao-de-cobertura: elevacao para a quote medida",
      f="src/BlazePhoenixRouter.sol",
      old="                if (bound < BPC.mulDiv(qs, MIN_QUOTE_COVERAGE_BPS, BPC.BPS)) bound = qs;",
      new="                qs; // MUTANTE",
      teste="test_BleedingLegHiddenInAHealthyTotalIsCaught"),
 dict(nome="portao-de-cobertura: o piso por perna",
      f="src/BlazePhoenixRouter.sol",
      old="            if (bound != 0 && got < BPC.mulDivUp(bound, BPC.LEG_FLOOR_BPS, BPC.BPS)) revert RouterE(5);",
      new="            bound; // MUTANTE",
      teste="test_BleedingLegHiddenInAHealthyTotalIsCaught"),
 dict(nome="FoT: a re-escala do piso pela medicao",
      f="src/BlazePhoenixRouter.sol",
      old="                    if (legNet < BPC.BPS) bound = BPC.mulDiv(bound, legNet, BPC.BPS);",
      new="                    legNet; // MUTANTE",
      teste="test_EntryTax25_OneLeg_MustSettle"),
 dict(nome="FoT: o fix-buraco (anular o piso em vez de o re-precar)",
      f="src/BlazePhoenixRouter.sol",
      old="""                if (fotAfter != fotBefore && bound != 0) {
                    uint256 legNet = fotBefore == 0
                        ? fotAfter
                        : BPC.mulDiv(fotAfter, BPC.BPS, fotBefore);
                    if (legNet < BPC.BPS) bound = BPC.mulDiv(bound, legNet, BPC.BPS);
                }""",
      new="                if (fotAfter != fotBefore) { bound = 0; } // MUTANTE",
      teste="test_FotIsNotAnExcuseToBleed"),
 dict(nome="theta: um bit da tabela de atributos",
      f="src/BlazePhoenixCore.sol",
      old="    uint256 internal constant THETA_ATTR = 0x040A9400A9;",
      new="    uint256 internal constant THETA_ATTR = 0x040A9400A8; // MUTANTE",
      teste="test_Parity_Reserves"),
 dict(nome="solidly: re-cegar os decimais na primitiva unica",
      f="src/BlazePhoenixCore.sol",
      old="        return outSolidlyStable(ain, rIn, rOut, liveFee, _decimalsOf(tokenIn), _decimalsOf(other));",
      new="        other; return outSolidlyStable(ain, rIn, rOut, liveFee, 0, 0); // MUTANTE",
      teste="test_FallbackPath_UnequalDecimals_MustStillSettle"),
 dict(nome="depthFromL: repor o L cru quando nao ha preco",
      f="src/BlazePhoenixCore.sol",
      old="    function depthFromL(uint128 liq, uint160 sp) internal pure returns (uint256) {\n        if (sp == 0) return 0;",
      new="    function depthFromL(uint128 liq, uint160 sp) internal pure returns (uint256) {\n        if (sp == 0) return uint256(liq); // MUTANTE",
      teste="test_NoPriceMeansNoDepth"),
 dict(nome="fee: a cobranca por hop (a fuga pelo prefixo de po)",
      f="src/BlazePhoenixRouter.sol",
      old="            amountIn = _chargeHopFee(hop, h, amountIn, foreignBase);",
      new="            foreignBase; // MUTANTE",
      teste="test_JUIZ_PrefixoSemValorEscapaAFee"),
 dict(nome="fee: so no hop 0 (a fuga que a ancora na entrada tinha)",
      f="src/BlazePhoenixRouter.sol",
      old="        uint256 feeH = BPC.mulDivUp(baseH, BPC.PROTOCOL_FEE_BPS, BPC.BPS);",
      new="        uint256 feeH = h == 0 ? BPC.mulDivUp(baseH, BPC.PROTOCOL_FEE_BPS, BPC.BPS) : 0; // MUTANTE",
      teste="test_JUIZ_PrefixoSemValorEscapaAFee"),
 dict(nome="fee: a baseline do sweep recalculada tarde (holds-nothing)",
      f="src/BlazePhoenixRouter.sol",
      old="        uint256 baseIn = tinStart > amountIn ? tinStart - amountIn : 0;",
      new="        uint256 baseIn = tinStart; // MUTANTE",
      teste="test_Refund_BestExactIn_ResidualGoesToPayer_NotRouter"),
 dict(nome="solver: a base da banda e a mediana PONDERADA (ponto de rutura 0 -> 50%)",
      f="src/BlazePhoenixSolver.sol",
      old="            if (acc >= metade) return r[i];",
      new="            if (acc >= metade) return r[m - 1]; // MUTANTE: um so sensor captura a base",
      teste="test_UmaPoolFundaNaoCapturaABanda"),
 dict(nome="solver: o peso do split vem da profundidade, nao do saldo (T2)",
      f="src/BlazePhoenixSolver.sol",
      old="            uint256 w = mx == 0 ? 1 : BPC.mulDiv(depth[i], 10_000, mx);",
      new="            uint256 w = mx == 0 ? 1 : BPC.mulDiv(bals[i], 10_000, mx); // MUTANTE",
      teste="test_DoacaoNaoCompraFatiaDoSplit"),
 dict(nome="router: a bijecao WETH nativa colapsada num produtor",
      f="src/BlazePhoenixCore.sol",
      old="        if (tokenOther == weth)  return (tokenIn, address(0));",
      new="        if (tokenOther == weth)  return (tokenIn, tokenOther); // MUTANTE",
      teste="test_LadoDoOutro"),
 dict(nome="router: eventos atribuidos ao pagador, nao ao msg.sender",
      f="src/BlazePhoenixRouter.sol",
      old="        emit ExecutionProof(payer, tokenOut, finalHopQuote, delivered, protocolFloorOut, block.number);",
      new="        emit ExecutionProof(msg.sender, tokenOut, finalHopQuote, delivered, protocolFloorOut, block.number); // MUTANTE",
      teste="test_SwapBest_EventosAtribuidosAoUtilizador"),
 dict(nome="quoter: a fee do preview compoe por hop",
      f="src/BlazePhoenixQuoter.sol",
      old="        afterFee -= BPC.mulDivUp(afterFee, BPC.PROTOCOL_FEE_BPS, BPC.BPS);",
      new="        afterFee -= 0; // MUTANTE",
      teste="test_DoisHops_PreviewBateComAEntrega"),
 dict(nome="solver: o filtro de hooks que alteram deltas",
      f="src/BlazePhoenixSolver.sol",
      old="            if (!BPC.hookAltersDeltas(reg[i].hooks)) { merged[n] = reg[i]; unchecked { ++n; } }",
      new="            { merged[n] = reg[i]; unchecked { ++n; } } // MUTANTE",
      teste="test_DeltaAlteringHookIsNeverRouted"),
 dict(nome="solver: a ordem canonica hookless-antes-de-hooked",
      f="src/BlazePhoenixSolver.sol",
      old="        _orderLegs(hop);",
      new="        // MUTANTE",
      teste="test_HooklessLegsComeFirst"),
 dict(nome="hub: a mascara de prova de par perde um kind vivo",
      f="src/BlazePhoenixHub.sol",
      old="        | (uint256(1) << BPC.KIND_SOLIDLY) | (uint256(1) << BPC.KIND_ALGEBRA);",
      new="        | (uint256(1) << BPC.KIND_SOLIDLY); // MUTANTE",
      teste="test_PairProofMaskMatchesTheta"),
 dict(nome="hub: o portao de kinds na SEGUNDA porta de registo",
      f="src/BlazePhoenixHub.sol",
      old="        if (((KINDS_EXECUTABLE >> kind) & 1) == 0) return;",
      new="        // MUTANTE",
      teste="test_RecordSwapRejectsExcisedKind"),
 # ── guardas da vaga de selagem 2026-08-31/09-01 ────────────────────────────
 # O CONTRATO deste ficheiro em accao: nove commits acrescentaram guardas e a
 # lista nao foi actualizada. Foi ele proprio que o apanhou, com tres ALVO
 # PERDIDO — os tres alvos que a selagem tinha movido de mulDiv para mulDivUp.
 dict(nome="balanceOf: uma leitura falhada volta a ser saldo zero",
      f="src/BlazePhoenixCore.sol",
      old='        require(ok, "BPC:balanceOf");',
      new="        ok; // MUTANTE",
      teste="test_FailedRead_IsReportedAsZeroBalance"),
 dict(nome="bridges: sem guarda de duplicados os dois produtores voltam a discordar",
      f="src/BlazePhoenixHub.sol",
      old="        if ($.isBridge[t]) return;",
      new="        // MUTANTE",
      teste="test_DupAddThenRemove_ArrayMappingDesync"),
 dict(nome="registo: creditar legs declaradas em vez das executadas (a leg fantasma)",
      f="src/BlazePhoenixRouter.sol",
      old="                if (!ran) { unchecked { ++l; } continue; }",
      new="                ran; // MUTANTE",
      teste="test_PhantomLeg_NotCreditedToRegistry"),
 dict(nome="V4: o grid volta a ser suprimido por um codigo aprendido",
      f="src/BlazePhoenixHub.sol",
      old="        if (kf >> 128 == kfBeforeOwnProbes) kf = _probeV4Batch(mgr, t0, t1, _v4GridTiers(), hits, kf);",
      new="        if (kf >> 128 == 0) kf = _probeV4Batch(mgr, t0, t1, _v4GridTiers(), hits, kf); // MUTANTE",
      teste="test_LearnedCode_DoesNotSuppressGridDiscovery"),
 dict(nome="kind: aceitar a declaracao da calldata contra a forma medida",
      f="src/BlazePhoenixHub.sol",
      old="            if (declaredConc != isConc) return;",
      new="            declaredConc; isConc; // MUTANTE",
      teste="test_ConcentratedPool_MustNotPersistAsV2"),
 dict(nome="kind: nao derivar a familia concentrada da forma da pool",
      f="src/BlazePhoenixHub.sol",
      old="            if (isConc) kind = dynShape ? BPC.KIND_ALGEBRA : BPC.KIND_V3;",
      new="            isConc; // MUTANTE",
      teste="test_AlgebraShapedPool_MustNotPersistAsV3"),
 # NOTA: a distincao media-vs-maximo NAO e alcancavel pela API do Solver — ele
 # escolhe sempre a melhor pool e nunca oferece uma leg destruidora, logo todas
 # as rotas deste par sao de UMA leg, onde media == maximo. O mutante abaixo
 # vigia o que E alcancavel: que o tecto continua ligado e a recusar.
 dict(nome="impacto: o tecto do Solver deixa de recusar (media ou maximo)",
      f="src/BlazePhoenixSolver.sol",
      old="        if (maxLegImpactBps >= MAX_ROUTE_IMPACT_BPS) return route;",
      new="        maxLegImpactBps; // MUTANTE",
      teste="test_ShallowPool_RouteIsRefused"),
 dict(nome="psi: bucketWeight deixa de dobrar, e a histerese desaparece em silencio",
      f="src/BlazePhoenixCore.sol",
      old="    function bucketWeight(uint8 b) internal pure returns (uint256) {\n        return uint256(1) << b;",
      new="    function bucketWeight(uint8 b) internal pure returns (uint256) {\n        return uint256(1) + b; // MUTANTE",
      teste="test_AdmissionMargin_IsNotRedundantWithQuantisation"),
 # ── pontos cegos apanhados a auditar a propria guarda (2026-09-01) ─────────
 # Os 27 cobriam a leg fantasma, o grid V4, o kind derivado, o desync das
 # bridges e o balanceOf. NAO cobriam os fixes de ARITMETICA da mesma vaga: o
 # sentido do arredondamento da fee, o sentinela da curva estavel, os dois
 # clamps do preview e a ponderacao do impacto. Um teste que corrige um bug
 # sem mutante a apontar-lhe nao esta provado a apanhar a regressao que existe
 # para impedir.
 dict(nome="fee: o arredondamento volta a ser para BAIXO (a fee que desaparece no po)",
      f="src/BlazePhoenixRouter.sol",
      old="        uint256 feeH = BPC.mulDivUp(baseH, BPC.PROTOCOL_FEE_BPS, BPC.BPS);",
      new="        uint256 feeH = BPC.mulDiv(baseH, BPC.PROTOCOL_FEE_BPS, BPC.BPS); // MUTANTE",
      teste="test_DustSwap_PaysAProtocolFee"),
 dict(nome="solidly: o sentinela volta a vigiar as reservas em vez do resultado",
      f="src/BlazePhoenixCore.sol",
      old="        if (!_solKFits(X + A, Y)) return 0;",
      new="        // MUTANTE",
      teste="test_ReservesInsideTheWindow_MustNotRevert"),
 dict(nome="quoter: a leg Solidly volta a re-escalar em vez de medir na pool",
      f="src/BlazePhoenixQuoter.sol",
      old="                    (legOut, ) = BPC.universalQuote(sc, legIn);",
      new="                    legOut = BPC.mulDiv(leg.expectedOut, legIn, base); // MUTANTE",
      teste="test_RED_SolidlyLeg_UpscaledQuoteExceedsPoolTruth"),
 dict(nome="quoter: o clamp do fallback concentrado extrapola outra vez pela tangente",
      f="src/BlazePhoenixQuoter.sol",
      old="                    // may keep the plan's own claim, never exceed it.\n                    if (legOut == 0)\n                        legOut = BPC.mulDiv(\n                            leg.expectedOut, legIn > base ? base : legIn, base);",
      new="                    // may keep the plan's own claim, never exceed it.\n                    if (legOut == 0)\n                        legOut = BPC.mulDiv(leg.expectedOut, legIn, base); // MUTANTE",
      teste="test_RED_ConcFallback_NeverScalesAbovePlan"),
 dict(nome="quoter: o clamp do fallback V4 extrapola outra vez pela tangente",
      f="src/BlazePhoenixQuoter.sol",
      old="                    // plan's point upward along the tangent.\n                    if (legOut == 0)\n                        legOut = BPC.mulDiv(\n                            leg.expectedOut, legIn > base ? base : legIn, base);",
      new="                    // plan's point upward along the tangent.\n                    if (legOut == 0)\n                        legOut = BPC.mulDiv(leg.expectedOut, legIn, base); // MUTANTE",
      teste="test_RED_V4Fallback_NeverScalesAbovePlan"),
 dict(nome="impacto: o termo deixa de ser ponderado pelo tamanho da leg (o po volta a votar)",
      f="src/BlazePhoenixRouter.sol",
      old="        return BPC.mulDiv(imp * legs, legAmountIn, scaleDen);",
      new="        return imp; // MUTANTE",
      teste="test_DustPadding_MustNotCollapseTheFloor"),
 dict(nome="callback: a porta de autenticacao v3 aceita quem nao e a pool esperada",
      f="src/BlazePhoenixRouter.sol",
      old="        if (msg.sender != expected || expected == address(0)) revert RouterE(6);",
      new="        if (expected == address(0)) revert RouterE(6); // MUTANTE",
      teste="test_ImpostorCallingTheCallbackMidSwapIsNeverPaid"),
 dict(nome="callback: o unlockCallback V4 aceita quem nao e o PoolManager",
      f="src/BlazePhoenixRouter.sol",
      old="        if (msg.sender != mgr) revert RouterE(6);",
      new="        mgr; // MUTANTE",
      teste="test_UnlockCallback_RevertsWhenNotV4Manager"),
 dict(nome="renounce: o Router volta a poder ossificar pausado (estado terminal)",
      f="src/BlazePhoenixRouter.sol",
      old="        if (paused) revert RouterE(2);\n        controlRenounced = true;",
      new="        controlRenounced = true; // MUTANTE",
      teste="test_Composition_PauseThenRenounce_IsRefused"),
 dict(nome="renounce: o Hub volta a poder ossificar pausado (registo surdo p/ sempre)",
      f="src/BlazePhoenixHub.sol",
      old="        if (_store().paused) revert HubE(2);\n        _store().controlRenounced = true;",
      new="        _store().controlRenounced = true; // MUTANTE",
      teste="test_Composition_HubPauseThenRenounce_IsRefused"),
 # ── operadores ausentes: relacional, &&/||, codigo de erro (2026-09-01) ───
 # A auditoria da PROPRIA lista encontrou a distribuicao coxa: ~14 mutantes de
 # delecao e ZERO de substituicao relacional, ZERO de troca de conector logico,
 # ZERO de troca de codigo de erro — ironico, porque o cabecalho deste ficheiro
 # nomeia "revert com o codigo certo da verificacao errada" como a assinatura
 # da casa. Tambem sem vigia: os guardas de entrada (deadline, minOut==0), o
 # whenLive das portas, e a APLICACAO do piso final (os mutantes existentes
 # vigiavam como o piso e CONSTRUIDO, nenhum vigiava a comparacao que o aplica).
 # Cada entrada abaixo foi verificada a matar o seu teste no box a 2026-09-01.
 dict(nome="piso aplicado: < vira <= na comparacao final delivered/userMinOut",
      f="src/BlazePhoenixRouter.sol",
      old="        if (delivered < userMinOut) revert RouterE(5);",
      new="        if (delivered <= userMinOut) revert RouterE(5); // MUTANTE",
      teste="test_MinOut_Boundary_ExactNetDelivers"),
 dict(nome="piso aplicado: um wei de folga na comparacao final",
      f="src/BlazePhoenixRouter.sol",
      old="        if (delivered < userMinOut) revert RouterE(5);",
      new="        if (delivered + 1 < userMinOut) revert RouterE(5); // MUTANTE",
      teste="test_MinOut_DeliveredShortfallIsRefused"),
 dict(nome="deadline: > vira >= na porta classica (a fronteira do prazo)",
      f="src/BlazePhoenixRouter.sol",
      old="""        if (block.timestamp > deadline) revert RouterE(4);
        if (route.hops.length == 0 || amountIn == 0) revert RouterE(3);
        address tokenIn  = route.hops[0].tokenIn;""",
      new="""        if (block.timestamp >= deadline) revert RouterE(4); // MUTANTE
        if (route.hops.length == 0 || amountIn == 0) revert RouterE(3);
        address tokenIn  = route.hops[0].tokenIn;""",
      teste="test_Deadline_ExpiredRefusedAndBoundaryHolds"),
 dict(nome="fee-no-output: >= vira > (a fee que consome o output inteiro passa)",
      f="src/BlazePhoenixRouter.sol",
      old="                if (fOut >= amountOut) revert RouterE(8);",
      new="                if (fOut > amountOut) revert RouterE(8); // MUTANTE",
      teste="test_FeeOnOut_OneWeiOutputWhollyConsumedIsRefused"),
 dict(nome="orcamento por hop: a folga atestada dobra (limite estrito vira frouxo)",
      f="src/BlazePhoenixRouter.sol",
      old="                if (hopGot + slack < hopAttested) revert RouterE(5);",
      new="                if (hopGot + slack + slack < hopAttested) revert RouterE(5); // MUTANTE",
      teste="test_TwoBleedingLegs_RevertOnHopBudget"),
 dict(nome="entrada: && vira || no guarda de minOut zero (a condicao inverte o alcance)",
      f="src/BlazePhoenixRouter.sol",
      old="""        if (amountIn > 0 && userMinOut == 0) revert RouterE(10);
        return _swap(route, amountIn, userMinOut, recipient, deadline);""",
      new="""        if (amountIn > 0 || userMinOut == 0) revert RouterE(10); // MUTANTE
        return _swap(route, amountIn, userMinOut, recipient, deadline);""",
      teste="test_INV6_zeroAmountIsNotTreatedAsAZeroMinOutSwap"),
 dict(nome="callback v3: || vira && na autenticacao (impostor com expected vivo passa)",
      f="src/BlazePhoenixRouter.sol",
      old="        if (msg.sender != expected || expected == address(0)) revert RouterE(6);",
      new="        if (msg.sender != expected && expected == address(0)) revert RouterE(6); // MUTANTE",
      teste="test_ImpostorCallingTheCallbackMidSwapIsNeverPaid"),
 dict(nome="onlyControl: || vira && (um estranho passa enquanto nao houver renounce)",
      f="src/BlazePhoenixRouter.sol",
      old="    modifier onlyControl() { if (msg.sender != admin || controlRenounced) revert RouterE(1); _; }",
      new="    modifier onlyControl() { if (msg.sender != admin && controlRenounced) revert RouterE(1); _; } // MUTANTE",
      teste="test_Control_EveryControlDoorRefusesAStranger"),
 dict(nome="codigo de erro: fee-consome-output troca 8 por 5 (o selector e a unica testemunha)",
      f="src/BlazePhoenixRouter.sol",
      old="                if (fOut >= amountOut) revert RouterE(8);",
      new="                if (fOut >= amountOut) revert RouterE(5); // MUTANTE",
      teste="test_FeeOnOut_OneWeiOutputWhollyConsumedIsRefused"),
 dict(nome="codigo de erro: minOut zero troca 10 por 3",
      f="src/BlazePhoenixRouter.sol",
      old="""        if (amountIn > 0 && userMinOut == 0) revert RouterE(10);
        return _swap(route, amountIn, userMinOut, recipient, deadline);""",
      new="""        if (amountIn > 0 && userMinOut == 0) revert RouterE(3); // MUTANTE
        return _swap(route, amountIn, userMinOut, recipient, deadline);""",
      teste="test_INV6_swapExactIn_rejectsZeroMinOut"),
 dict(nome="whenLive: o modificador cai da porta classica (pausado deixa de travar)",
      f="src/BlazePhoenixRouter.sol",
      old="""    function swapExactIn(
        Route calldata route, uint256 amountIn, uint256 userMinOut,
        address recipient, uint256 deadline
    ) external whenLive nrEntrant returns (uint256) {""",
      new="""    function swapExactIn(
        Route calldata route, uint256 amountIn, uint256 userMinOut,
        address recipient, uint256 deadline
    ) external nrEntrant returns (uint256) { // MUTANTE""",
      teste="test_SetPaused_BlocksSwaps"),
 dict(nome="fee-no-output: mulDivUp vira mulDiv (a fee de 1 wei desaparece no po)",
      f="src/BlazePhoenixRouter.sol",
      old="            uint256 fOut = BPC.mulDivUp(amountOut, BPC.PROTOCOL_FEE_BPS, BPC.BPS);",
      new="            uint256 fOut = BPC.mulDiv(amountOut, BPC.PROTOCOL_FEE_BPS, BPC.BPS); // MUTANTE",
      teste="test_FeeOnOut_OneWeiOutputWhollyConsumedIsRefused"),
 dict(nome="constante: MAX_LEGS_PER_HOP empurrada de 5 para 4 (a fronteira, nao a remocao)",
      f="src/BlazePhoenixRouter.sol",
      old="    uint8   internal constant MAX_LEGS_PER_HOP  = 5;",
      new="    uint8   internal constant MAX_LEGS_PER_HOP  = 4; // MUTANTE",
      teste="test_G8_FiveLegs_BoundaryPasses"),
 # ── as duas fronteiras exatas antes REJEITADAS (2026-09-01) ────────────────
 # Os dois flips < -> <= abaixo tinham ficado FORA da lista por falta de teste
 # que pousasse na igualdade (os testes do orcamento viviam a 82%/85%; o do
 # minOut controlava delivered, nao amountOut). Provado que NAO sao
 # equivalentes: a fronteira e alcancavel para QUALQUER quote G — no caso do
 # orcamento com hopAttested = S = 10*floor(2G/9) + (2G mod 9) (a funcao
 # S - floor(S/10) percorre todos os inteiros), no caso do piso com
 # singleOutFloor = amountOut (identidade de calldata). A chave de exatidao em
 # ambos: amountIn = soma(leg.amountIn) + fee pre-paga -> scaleNum == scaleDen
 # -> os mulDiv de escala sao identidades. Kill verificado no box 2026-09-01:
 # cada teste PASSA limpo e FALHA RouterE(5) com o seu mutante, com o vizinho
 # verde (atribuicao de sitio limpa nos dois sentidos).
 dict(nome="orcamento por hop: < vira <= (a fronteira exata, nao a folga dobrada)",
      f="src/BlazePhoenixRouter.sol",
      old="                if (hopGot + slack < hopAttested) revert RouterE(5);",
      new="                if (hopGot + slack <= hopAttested) revert RouterE(5); // MUTANTE",
      teste="test_HopBudget_ExactBoundaryDelivers"),
 dict(nome="piso agregado: < vira <= na comparacao amountOut/effMin",
      f="src/BlazePhoenixRouter.sol",
      old="        if (amountOut < effMin) revert RouterE(5);",
      new="        if (amountOut <= effMin) revert RouterE(5); // MUTANTE",
      teste="test_AggregateFloor_ExactBoundaryDelivers"),
 # ── as doze guardas que nunca tinham disparado (2026-09-01) ────────────────
 # Um inventario classificou 29 sitios de recusa como conduzidos de um so lado.
 # Doze eram ALCANCAVEIS e tinham testemunha derivada; o test/GuardsNeverFired
 # faz cada uma disparar com o codigo EXATO. Metade partilha o codigo de erro
 # com uma guarda vizinha, e por isso um expectRevert nu passaria na errada.
 dict(nome="hook: o pin de codehash na EXECUCAO (Layer 3) deixa de pausar",
      f="src/BlazePhoenixRouter.sol",
      old="            if (!hub.isHookLive(leg.hooks)) revert RouterE(9);",
      new="            // MUTANTE",
      teste="test_W1_FireB_MutatedHookCode_Reverts9"),
 dict(nome="deadline: a verificacao das portas pre-pulled cai",
      f="src/BlazePhoenixRouter.sol",
      old="        address recipient, uint256 deadline, address payer\n    ) private returns (uint256) {\n        if (block.timestamp > deadline) revert RouterE(4);",
      new="        address recipient, uint256 deadline, address payer\n    ) private returns (uint256) {\n        deadline; // MUTANTE",
      teste="test_W2_Permit2Door_DeadlinePassed_Reverts4"),
 dict(nome="solver hostil: o fail-closed antes do pull cai",
      f="src/BlazePhoenixRouter.sol",
      old="        if (\n            plan.best.hops.length == 0 || plan.best.hops[0].tokenIn != tokenIn\n                || plan.best.hops[plan.best.hops.length - 1].tokenOut != tokenOut\n        ) revert RouterE(3); // fail-closed",
      new="        // MUTANTE",
      teste="test_W3_FireB_TokenInMismatchPlan_Reverts3_BeforeAnyPull"),
 dict(nome="V4: o portao auxId==0 cai (o vizinho com o mesmo codigo 8 nao o cobre)",
      f="src/BlazePhoenixRouter.sol",
      old="        address tokenOther = address(uint160(uint256(leg.auxId)));\n        if (tokenOther == address(0)) revert RouterE(8);",
      new="        address tokenOther = address(uint160(uint256(leg.auxId)));\n        // MUTANTE",
      teste="test_W4_Fire_V4LegAuxIdZero_Reverts8"),
 dict(nome="mulDiv: a require da reducao 512->256 cai",
      f="src/BlazePhoenixCore.sol",
      old='            require(d > prod1, "BPC:mulDiv");',
      new="            // MUTANTE",
      teste="test_W5_Fire_MulDivResultOverflows_Reverts"),
 dict(nome="claimV4: c0==c1 cai na porta permissionless",
      f="src/BlazePhoenixHub.sol",
      old="        _ne0(c0); _ne0(c1);                 // native currency (address(0)) rejected\n        if (c0 == c1) revert HubE(4);",
      new="        _ne0(c0); _ne0(c1);                 // native currency (address(0)) rejected\n        // MUTANTE",
      teste="test_W6_Fire_ClaimV4EqualCurrencies_Reverts4"),
 dict(nome="addFactory: o emparelhamento fees/spacings do modo 9 cai",
      f="src/BlazePhoenixHub.sol",
      old="            if (fees.length != spacings.length) revert HubE(5);",
      new="            // MUTANTE",
      teste="test_W7_Fire_Mode9UnpairedFees_Reverts5"),
 dict(nome="porta nativa: a recusa de rota vazia cai (vira Panic 0x32)",
      f="src/BlazePhoenixRouter.sol",
      old="        if (route.hops.length == 0) revert RouterE(3);\n        if (route.hops[0].tokenIn != w) revert RouterE(3);   // route must start in WETH",
      new="        if (route.hops[0].tokenIn != w) revert RouterE(3);   // route must start in WETH // MUTANTE",
      teste="test_W8_Fire_NativeDoorEmptyRoute_Reverts3"),
 dict(nome="rescue: o destino zero passa a poder ser posto em fila",
      f="src/BlazePhoenixRouter.sol",
      old="    function queueRescue(address token, address to) external onlyControl {\n        if (to == address(0)) revert RouterE(3);",
      new="    function queueRescue(address token, address to) external onlyControl {\n        // MUTANTE",
      teste="test_W9_Fire_QueueRescueZeroTo_Reverts3"),
 dict(nome="addV4: c0==c1 cai na porta do operador",
      f="src/BlazePhoenixHub.sol",
      old="        _ne0(c1);\n        if (c0 == c1) revert HubE(4);",
      new="        _ne0(c1);\n        // MUTANTE",
      teste="test_W10_Fire_AddV4EqualCurrencies_Reverts4"),
 dict(nome="construtor do Router: os tres bracos zero deixam de recusar",
      f="src/BlazePhoenixRouter.sol",
      old="        if (hub_ == address(0) || solver_ == address(0) || admin_ == address(0)) revert RouterE(3);",
      new="        // MUTANTE",
      teste="test_W11_FireA_CtorZeroHub_Reverts3"),
 dict(nome="construtor do Solver: o hub zero deixa de recusar",
      f="src/BlazePhoenixSolver.sol",
      old='        require(hub_ != address(0), "Solver:hub0");',
      new="        // MUTANTE",
      teste="test_W12_Fire_SolverCtorZeroHub_Reverts"),
 # ── o cadeado de reentrancia, que nao tinha vigia nenhuma ──────────────────
 # O `invariant_reentrancyBlocked` contava como cobertura e era uma TAUTOLOGIA:
 # o sentinela so virava se uma chamada aninhada REGRESSASSE, e a carga dele era
 # uma rota vazia — que reverte RouterE(3) com cadeado e sem cadeado. Estava
 # preso ao valor seguro em todas as versoes possiveis do contrato. Duas
 # maneiras distintas de o cadeado falhar, dois vectores, dois testes.
 dict(nome="reentrancia: a verificacao do cadeado deixa de recusar (regiao V4 bloqueada)",
      f="src/BlazePhoenixRouter.sol",
      old="        if (v != 0) revert RouterE(7);",
      new="        v; // MUTANTE",
      teste="test_NestedReentryDuringV4Settle_BlockedByExactLockCode"),
 dict(nome="reentrancia: o cadeado nunca chega a ser armado (a puxada de tokens)",
      f="src/BlazePhoenixRouter.sol",
      old="        assembly { tstore(s, 1) }",
      new="        // MUTANTE",
      teste="test_ReentrancyGuard_BlocksNestedSwapExactInDuringTokenPull"),
 # ── review 2026-09-02: T19 (the poolDeployer pin), the V2/Solidly refuter, the
 # tier in the freshness gate, allowHook's removal arm, and the A1 doors ────────
 # Three read-only reviewers over main 19b2f08. Every entry was judged on the
 # CI box BEFORE it entered this list: mutant applied -> the named test goes
 # red, its neighbour stays green. Where one `old` serves two mutants (the R-B
 # ceiling) the list applies them one at a time, so both are valid.
 dict(nome="T19: the poolDeployer pin at admission is dropped (the attested origin is never written)",
      f="src/BlazePhoenixHub.sol",
      old="            $.factoryDeployer[factory] = BPC.resolvePoolDeployer(factory);",
      new="            factory; // MUTANTE",
      teste="test_T19_AnswerSwap_DerivesFromAttestedDeployer"),
 dict(nome="T19: the Algebra derive origin is the LIVE answer again",
      f="src/BlazePhoenixHub.sol",
      old="            address orig = _store().factoryDeployer[fac.factory];",
      new="            address orig = BPC.resolvePoolDeployer(fac.factory); // MUTANTE",
      teste="test_T19_ResolverDies_AttestedPoolStaysServed"),
 dict(nome="T19: the predicate loses fee == 0 (a fee-3000 V3 row derives with the Algebra salt)",
      f="src/BlazePhoenixHub.sol",
      old="        if (fac.mode == MODE_CREATE2_V3 && fee == 0) {",
      new="        if (fac.mode == MODE_CREATE2_V3) { // MUTANTE",
      teste="test_T19_PlainV3Mode5_FeeInSalt_FactoryOrigin"),
 dict(nome="T19: the factory fallback is dropped (a zero origin derives elsewhere)",
      f="src/BlazePhoenixHub.sol",
      old="            if (orig == address(0)) orig = fac.factory;",
      new="            // MUTANTE",
      teste="test_T19_NoResolverAtAdmission_FactoryIsOrigin"),
 dict(nome="kind: the pair-shaped family takes the declaration again (V2 vs Solidly)",
      f="src/BlazePhoenixHub.sol",
      old="            if (!isConc) kind = BPC.isSolidlyShaped(pool) ? BPC.KIND_SOLIDLY : BPC.KIND_V2;",
      new="            isConc; // MUTANTE",
      teste="test_SolidlyShapedPool_MustNotPersistAsV2"),
 dict(nome="freshness gate: permissionless rows can switch discovery off again",
      f="src/BlazePhoenixSolver.sol",
      old="            if (BPC.decodeTier(s) != 0) { unchecked { ++i; } continue; }",
      new="            // MUTANTE",
      teste="test_ThreeSelfRegisteredDustRows_CannotSilenceDiscovery"),
 dict(nome="allowHook: the removal arm survives renounceControl again",
      f="src/BlazePhoenixHub.sol",
      old="        if (!ok && $.controlRenounced) revert HubE(1);",
      new="        // MUTANTE",
      teste="test_AfterRenounce_DelistingAHookIsRefused"),
 dict(nome="A1 door 2 (permit2): the zero-minOut refusal is dropped",
      f="src/BlazePhoenixRouter.sol",
      old="        if (amountIn > 0 && userMinOut == 0) revert RouterE(10);\n        if (permit.permitted.amount < amountIn) revert RouterE(3);",
      new="        if (permit.permitted.amount < amountIn) revert RouterE(3); // MUTANTE",
      teste="test_A1_Door2_Permit2_RefusesZeroMinOut"),
 dict(nome="A1 door 3 (native): the zero-minOut refusal is dropped",
      f="src/BlazePhoenixRouter.sol",
      old="        if (userMinOut == 0) revert RouterE(10);\n        if (route.hops.length == 0) revert RouterE(3);\n        if (route.hops[0].tokenIn != w) revert RouterE(3);   // route must start in WETH",
      new="        if (route.hops.length == 0) revert RouterE(3); // MUTANTE\n        if (route.hops[0].tokenIn != w) revert RouterE(3);   // route must start in WETH",
      teste="test_A1_Door3_Native_RefusesZeroMinOut"),
 dict(nome="A1 door 4 (swapBestExactIn): the zero-minOut refusal is dropped, before the solve",
      f="src/BlazePhoenixRouter.sol",
      old="        uint256 userMinOut, address recipient, uint256 deadline\n    ) external whenLive nrEntrant returns (uint256) {\n        if (amountIn == 0 || amountIn > type(uint128).max) revert RouterE(3);\n        if (userMinOut == 0) revert RouterE(10);",
      new="        uint256 userMinOut, address recipient, uint256 deadline\n    ) external whenLive nrEntrant returns (uint256) {\n        if (amountIn == 0 || amountIn > type(uint128).max) revert RouterE(3);\n        // MUTANTE",
      teste="test_A1_Door4_Best_RefusesZeroMinOut_BeforeTheSolve"),
 dict(nome="A1 door 5 (self-call): the door stops requiring msg.sender == this",
      f="src/BlazePhoenixRouter.sol",
      old="        if (msg.sender != address(this)) revert RouterE(1);",
      new="        // MUTANTE",
      teste="test_A1_Door5_SelfCall_StrangerIsRefused"),
 dict(nome="factory codehash pin (modes 0-3): dropped",
      f="src/BlazePhoenixHub.sol",
      old="        if (fac.mode < 4 && fac.factory.codehash != _store().factoryCodehash[fac.factory]) return k;",
      new="        // MUTANTE",
      teste="test_RuntimeMutatedFactoryStopsBeingADiscoverySource"),
 dict(nome="R-B ceiling, multi-hop: the worst-leg arm is dropped (only the mean gates)",
      f="src/BlazePhoenixSolver.sol",
      old="        if (maxLegImpactBps >= MAX_ROUTE_IMPACT_BPS || totalImpactBps >= MAX_ROUTE_IMPACT_BPS) return route;",
      new="        if (totalImpactBps >= MAX_ROUTE_IMPACT_BPS) return route; // MUTANTE",
      teste="test_L1498c1_WorstLegArmAloneRefusesTheDilutedDestroyer"),
 dict(nome="R-B ceiling, multi-hop: the aggregate arm is dropped (only the worst leg gates)",
      f="src/BlazePhoenixSolver.sol",
      old="        if (maxLegImpactBps >= MAX_ROUTE_IMPACT_BPS || totalImpactBps >= MAX_ROUTE_IMPACT_BPS) return route;",
      new="        if (maxLegImpactBps >= MAX_ROUTE_IMPACT_BPS) return route; // MUTANTE",
      teste="test_L1498c2_AggregateArmAloneRefusesTwoHalfImpactHops"),
 dict(nome="balanceOf: an empty return becomes a refusal instead of zero (the unset token)",
      f="src/BlazePhoenixCore.sol",
      old="                if iszero(lt(returndatasize(), 32)) { b := mload(m) }",
      new="                if iszero(lt(returndatasize(), 32)) { b := mload(m) }\n                if lt(returndatasize(), 32) { ok := 0 } // MUTANTE",
      teste="test_BalanceOf_CodelessIsDeliberateZero_NotARefusal"),
 dict(nome="NM-002: the floor no longer falls back to the attested quote when the last hop's quote is zero",
      f="src/BlazePhoenixRouter.sol",
      old="            if (h + 1 == route.hops.length && finalHopQuote == 0) finalHopQuote = hopAttested;",
      new="            // MUTANTE",
      teste="test_LiquidityGapOnLastHop_FloorFallsBackToAttested"),
 dict(nome="impact: an unquotable concentrated leg counts BPS again (the floor collapses to the clamp)",
      f="src/BlazePhoenixRouter.sol",
      old="                        q_ == 0 ? BPC.DEFAULT_IMPACT_BPS : BPC.impactV3FromOut(q_, legAmt, sp, leg.zeroForOne),",
      new="                        BPC.impactV3FromOut(q_, legAmt, sp, leg.zeroForOne), // MUTANTE",
      teste="test_UnquotableFeeZeroLeg_FloorDoesNotCollapseToTheClamp"),
 dict(nome="swapBestExactIn: the plan's output end is no longer checked",
      f="src/BlazePhoenixRouter.sol",
      old="                || plan.best.hops[plan.best.hops.length - 1].tokenOut != tokenOut\n        ) revert RouterE(3); // fail-closed",
      new="        ) revert RouterE(3); // fail-closed // MUTANTE",
      teste="test_PlanEndingInAnotherToken_IsRefusedBeforeThePull"),
 dict(nome="per-leg floor: mulDivUp becomes mulDiv in the 3/2 window (the 1-wei threshold rounds to zero)",
      f="src/BlazePhoenixRouter.sol",
      old="            if (bound != 0 && got < BPC.mulDivUp(bound, BPC.LEG_FLOOR_BPS, BPC.BPS)) revert RouterE(5);",
      new="            if (bound != 0 && got < BPC.mulDiv(bound, BPC.LEG_FLOOR_BPS, BPC.BPS)) revert RouterE(5); // MUTANTE",
      teste="test_OneWeiBound_LegDeliveringNothingIsRefused"),
 dict(nome="registry: a pair-shaped row's fee comes from the V3 getter again",
      f="src/BlazePhoenixHub.sol",
      old="            feeReg = isConc ? (dynShape ? 0 : BPC.getV3Fee(pool)) : 0;",
      new="            feeReg = dynShape ? 0 : BPC.getV3Fee(pool); // MUTANTE",
      teste="test_V2PairWithForeignFeeGetter_RowFeeIsZero"),
 dict(nome="resolvePoolDeployer: the >= 32 policy becomes == 32 again (a wide answer reads as zero)",
      f="src/BlazePhoenixCore.sol",
      old="            if and(ok, iszero(lt(returndatasize(), 32))) {",
      new="            if and(ok, eq(returndatasize(), 32)) { // MUTANTE",
      teste="test_T19_WideAnswerFactory_IsAttestedFromTheFirstWord"),
 # ── 6th bounty wave (mohaseenkatika), 2026-09-02: one floor, two producers ────
 dict(nome="solver floor: the attested floor rounds DOWN again (1 wei under the Router's)",
      f="src/BlazePhoenixSolver.sol",
      old="        uint256 floorOut = BPC.mulDivUp(hop.expectedOut, floorBps, BPC.BPS);",
      new="        uint256 floorOut = BPC.mulDiv(hop.expectedOut, floorBps, BPC.BPS); // MUTANTE",
      teste="test_Parity_SingleLegRoute_AttestedFloorEqualsEnforcedFloor"),
 dict(nome="solver floor: the hop impact is the UNWEIGHTED mean again (dust votes like a whole leg)",
      f="src/BlazePhoenixSolver.sol",
      old="            totalImpactBps += hopIn == 0 ? li : BPC.mulDiv(li * legs, hop.legs[i].amountIn, hopIn);",
      new="            totalImpactBps += li; // MUTANTE",
      teste="test_Parity_SplitRoute_AttestedFloorEqualsEnforcedFloor"),
 # ── frozen-at-write probes (7th bounty wave, 2026-09-02): the CONTROLS must have teeth ──
 dict(nome="hook liveness: drop the live codehash comparison",
      f="src/BlazePhoenixHub.sol",
      old="        return $.hookAllowed[h] && h.codehash == $.hookCodehash[h];",
      new="        return $.hookAllowed[h]; // MUTANT",
      teste="test_control_hookCodehash_isPinnedAtAdmissionAndReadLive"),
 dict(nome="register: forget the key-existence guard (duplicate rows)",
      f="src/BlazePhoenixHub.sol",
      old="        if ($.poolOf[key] == address(0)) {",
      new="        if (true) { // MUTANT",
      teste="test_control_tier_isRefreshedInPlaceBySeedPool"),
 dict(nome="solidly quote: skip the pool's own getAmountOut",
      f="src/BlazePhoenixCore.sol",
      old="            out = solidlyGetAmountOut(c.pool, amountIn, c.tokenIn);",
      new="            out = 0; // MUTANT",
      teste="test_control_stableField_standardPoolIsPricedByItsOwnGetter"),
 # ── the fixes behind the probes (7th bounty wave): each producer must be the one read ──
 dict(nome="BRIDGE-01: the bridge term of psi stops following the live bridge",
      f="src/BlazePhoenixHub.sol",
      old="        return _isRoutableBridge($, t0) || _isRoutableBridge($, t1);\n    }",
      new="        t0; t1; return false; // MUTANT\n    }",
      teste="test_probe_bridgedBit_removeBridge_psiFollowsTheLiveBridge"),
 dict(nome="BRIDGE-01 (mirror): a pool registered before addBridge must earn the bonus",
      f="src/BlazePhoenixHub.sol",
      old="        return _isRoutableBridge($, t0) || _isRoutableBridge($, t1);\n    }",
      new="        t0; t1; return false; // MUTANT\n    }",
      teste="test_probe_bridgedBit_addBridge_psiFollowsTheLiveBridge"),
 dict(nome="SLOT-01: the stable bit is never written at registration",
      f="src/BlazePhoenixHub.sol",
      old="        if (kind == BPC.KIND_SOLIDLY && BPC.solidlyStable(pool)) s = _markStable(s, true);",
      new="        pool; // MUTANT",
      teste="test_probe_stableField_registryReadReturnsThePoolsAnswer"),
 dict(nome="SLOT-01: the fallback curve reads a constant instead of the registry flag",
      f="src/BlazePhoenixHub.sol",
      old="        p.stable      = _isStable(s);",
      new="        p.stable      = false; // MUTANT",
      teste="test_probe_stableField_fallbackCurveReadsTheRegistryFlag"),
 dict(nome="PROV-01: declared reserves are no longer capped by physical holdings (Solver)",
      f="src/BlazePhoenixSolver.sol",
      old="                    if (physical < depths[i]) depths[i] = physical == 0 ? 1 : physical;",
      new="                    physical; // MUTANT",
      teste="test_probe_forgedMass_cannotCaptureTheRouteWithoutCapital"),
 # ── the multi-hop twin of the floor (found by the review pass after PR #25) ──
 dict(nome="floor, multi-hop: a leg's impact stops being weighted by its share",
      f="src/BlazePhoenixSolver.sol",
      old="                weightedAcc += hopIn == 0 ? li : BPC.mulDiv(li * legs, hops[h].legs[i].amountIn, hopIn);",
      new="                weightedAcc += li; // MUTANT",
      teste="test_Parity_TwoHopSplitRoute_AttestedFloorRateEqualsEnforcedFloorRate"),
 dict(nome="floor, multi-hop: the sum of per-hop means feeds the floor again",
      f="src/BlazePhoenixSolver.sol",
      old="        uint256 totalImpactBps = totalLegs > 0 ? weightedAcc / totalLegs : 0;",
      new="        uint256 totalImpactBps = gateImpactBps; weightedAcc; // MUTANT",
      teste="test_Parity_TwoHopSplitRoute_AttestedFloorRateEqualsEnforcedFloorRate"),
 # ── the review pass after PR #25 (2026-09-02): authority, gas-bomb, hop ceiling ──
 dict(nome="hooks: after renunciation a mutated hook can be re-armed again",
      f="src/BlazePhoenixHub.sol",
      old="        if (ok && $.controlRenounced && $.hookAllowed[h] && $.hookCodehash[h] != h.codehash) revert HubE(1);",
      new="        // MUTANT",
      teste="test_RenouncedAdmin_CanStillRearmMutatedHook"),
 dict(nome="V4 index: seedPool stops writing the O(1) entry for a V4 row",
      f="src/BlazePhoenixHub.sol",
      old="                $.v4EntryOf[key] = $.v4Entries.length;\n            }\n        }\n        _register(key, pool, kind, fee, hooks, t0, t1, true);",
      new="                // MUTANT\n            }\n        }\n        _register(key, pool, kind, fee, hooks, t0, t1, true);",
      teste="test_SeedPoolV4Row_FallsIntoUnboundedScan"),
 dict(nome="V4 index: the step-5 backstop stops answering (recovery gives up)",
      f="src/BlazePhoenixHub.sol",
      old="        uint256 ep = $.v4EntryOf[key];\n        if (ep != 0) {\n            ts = $.v4Entries[ep - 1].tickSpacing;",
      new="        uint256 ep = 0; key; // MUTANT\n        if (ep != 0) {\n            ts = $.v4Entries[ep - 1].tickSpacing;",
      teste="test_RecordSwap_WalksTheArrayUpToTheRowsIndex"),
 dict(nome="router: the hop ceiling is gone",
      f="src/BlazePhoenixRouter.sol",
      old="        if (route.hops.length > MAX_HOPS) revert RouterE(3);",
      new="        // MUTANT",
      teste="test_RouteHopCountHasACeiling"),
 dict(nome="router: Layer 2 falls back to per-hop scope (the hooked flag resets every hop)",
      f="src/BlazePhoenixRouter.sol",
      old="            uint256 hopGot;",
      new="            uint256 hopGot; sawHooked = false; // MUTANT",
      teste="test_HookedLegInHop0_BeforeHookless_Reverts"),
]

def run(t):
    r = subprocess.run(["forge","test","--match-test",t],
                       capture_output=True, text=True,
                       env={**os.environ,"FOUNDRY_PROFILE":"release"})
    return r.returncode == 0, r.stdout + r.stderr

def main():
    falhas = []
    for i, m in enumerate(M, 1):
        src = open(m["f"]).read()
        if src.count(m["old"]) != 1:
            falhas.append(f"[{i}] {m['nome']}: o alvo do mutante nao existe (ou ha varios) em {m['f']}. "
                          f"O codigo mudou e esta lista nao foi atualizada.")
            print(f"  [{i}] ALVO PERDIDO  {m['nome']}"); continue
        bak = src
        try:
            open(m["f"],"w").write(src.replace(m["old"], m["new"]))
            ok, out = run(m["teste"])
            if ok:
                falhas.append(f"[{i}] {m['nome']}: o teste '{m['teste']}' PASSOU com o guarda mutado. "
                              f"O guarda esta sem vigia — o teste e decorativo.")
                print(f"  [{i}] DECORATIVO   {m['nome']}  ({m['teste']} passou mutado)")
            elif "No tests match" in out or "Compiler run failed" in out:
                falhas.append(f"[{i}] {m['nome']}: o teste '{m['teste']}' nao existe.")
                print(f"  [{i}] TESTE AUSENTE {m['nome']}")
            else:
                print(f"  [{i}] ok           {m['nome']}")
        finally:
            open(m["f"],"w").write(bak)
    print()
    if falhas:
        print("GUARDAS SEM VIGIA:"); [print("  -", f) for f in falhas]
        sys.exit(1)
    print(f"{len(M)}/{len(M)} guardas com teste que os apanha.")

if __name__ == "__main__":
    main()
