// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.36;

// =============================================================================
//  RegimeHarness — one fixture builder and one assertion for every row of the
//  regime covering array (test/regime/RegimeCoverage.t.sol, generated by
//  .github/scripts/assurance/covering_array.py).
//
//  A row fixes the state no argument varies: venue family, hop count, legs per
//  hop, whether the input or the intermediate token is a registered bridge,
//  fee-on-transfer shape, the input token's decimals, the door the value came
//  in through, whether control has been renounced, whether the pair is full.
//  The assertion is the same for every row, which is what lets rows be
//  generated instead of written:
//
//      the swap SETTLES — delivered equals the recipient's balance delta, is at
//      least the floor the Router emitted, and the Router holds nothing after —
//      or it is REFUSED with a selector of ours (RouterE / SolverE / HubE /
//      QuoterE, or a "BPC:" revert string).
//
//  A panic, an empty revert, a foreign selector, a delivered amount that is
//  not the balance delta, or a balance left on the Router fails the row. A
//  row the fixture cannot build is reported NOT_CONSTRUCTIBLE and counts
//  against the denominator in docs/assurance/regimes-covering.json.
//
//  Outcomes are printed as `ROW <id> <OUTCOME> ...` for
//  .github/scripts/assurance/regime_summary.py.
// =============================================================================

import {Test, Vm, console2} from "forge-std/Test.sol";
import {BlazePhoenixHub} from "../../src/BlazePhoenixHub.sol";
import {BlazePhoenixSolver} from "../../src/BlazePhoenixSolver.sol";
import {BlazePhoenixRouter, IPermit2} from "../../src/BlazePhoenixRouter.sol";
import {BlazePhoenixCore as BPC, Route, Hop, Leg, RoutePlan} from "../../src/BlazePhoenixCore.sol";
import {MockERC20} from "../mocks/MockERC20.sol";
import {PathologicalERC20} from "../mocks/PathologicalERC20.sol";
import {MockV2Pair} from "../mocks/MockV2Pair.sol";
import {MockV3Pool} from "../mocks/MockV3Pool.sol";
import {MockSolidlyPair} from "../mocks/MockSolidlyPair.sol";
import {MockPermit2} from "../mocks/MockPermit2.sol";
import {TransferFromTaxERC20} from "../PartialFotAtPrePulledDoors.t.sol";
import {Outcomes} from "./Outcomes.sol";

library F {
    enum Kind { V2, V3, SOLIDLY }
    enum Hops { H1, H2, H3 }
    enum Legs { L1, L2 }
    enum InB  { IN_PLAIN, IN_BRIDGE }
    enum MidB { MID_PLAIN, MID_BRIDGE }
    enum Fot  { FOT_NONE, FOT_PULL, FOT_ALL }
    enum Dec  { D18, D6 }
    enum Door { EXACT_IN, BEST, PERMIT2 }
    enum Ctl  { LIVE, RENOUNCED }
    enum Full { PAIR_OPEN, PAIR_FULL }
}

interface IERC20Min {
    function balanceOf(address) external view returns (uint256);
    function approve(address, uint256) external returns (bool);
}

abstract contract RegimeHarness is Test {
    struct Row {
        F.Kind kind;
        F.Hops hops;
        F.Legs legs;
        F.InB  inBridge;
        F.MidB midBridge;
        F.Fot  fot;
        F.Dec  decimalsIn;
        F.Door door;
        F.Ctl  control;
        F.Full pairFull;
    }

    BlazePhoenixHub    hub;
    BlazePhoenixSolver solver;
    BlazePhoenixRouter router;
    MockPermit2        permit2;
    address user = address(0xBEEF);

    uint256 constant DEPTH_UNITS = 1_000_000;   // per side, in whole tokens
    uint256 constant AMOUNT_UNITS = 1_000;      // 0.1 % of depth
    uint16  constant FOT_BPS = 300;             // 3 % tax
    uint128 constant V3_LIQ = 1_000_000e18;

    address[] path;          // tokenIn, intermediates..., tokenOut
    address[] pools;         // every pool seeded for this row
    string    notBuilt;      // empty when the fixture was built

    // ------------------------------------------------------------------ build

    function _stack() private {
        hub = new BlazePhoenixHub(address(this));
        hub.initialize(address(this), address(0));
        solver = new BlazePhoenixSolver(address(hub));
        router = new BlazePhoenixRouter(address(hub), address(solver), address(this), address(0xFEE1), address(0xFEE2));
        hub.setRoles(address(router), address(solver), address(this));
        permit2 = new MockPermit2();
        router.setPermit2(address(permit2));
    }

    function _tokenIn(Row memory r) private returns (address t) {
        if (r.fot == F.Fot.FOT_PULL) {
            if (r.decimalsIn == F.Dec.D6) { notBuilt = "pull-only tax token has no 6-decimal form"; return address(0); }
            return address(new TransferFromTaxERC20("In", "IN"));
        }
        if (r.decimalsIn == F.Dec.D6) {
            PathologicalERC20 p = new PathologicalERC20("In", "IN", 6);
            if (r.fot == F.Fot.FOT_ALL) p.setFeeOnTransferBps(FOT_BPS);
            return address(p);
        }
        MockERC20 m = new MockERC20("In", "IN");
        if (r.fot == F.Fot.FOT_ALL) m.setFeeOnTransferBps(FOT_BPS);
        return address(m);
    }

    function _mint(address t, address to, uint256 units) private {
        uint256 amt = units * 10 ** _dec(t);
        if (t == path[0] && _isTax(t)) TransferFromTaxERC20(t).mint(to, amt);
        else if (t == path[0] && _isPath(t)) PathologicalERC20(t).mint(to, amt);
        else MockERC20(t).mint(to, amt);
    }

    function _dec(address t) private view returns (uint8) {
        (bool ok, bytes memory d) = t.staticcall(abi.encodeWithSignature("decimals()"));
        return ok && d.length >= 32 ? uint8(abi.decode(d, (uint256))) : 18;
    }

    bool private taxIn; bool private pathIn;
    function _isTax(address t) private view returns (bool) { return taxIn && t == path[0]; }
    function _isPath(address t) private view returns (bool) { return pathIn && t == path[0]; }

    function _sorted(address a, address b) private pure returns (address, address) {
        return a < b ? (a, b) : (b, a);
    }

    /// One pool of the row's family on (a, b), seeded into the Hub. Returns false if the
    /// Hub refused the row (a full pair whose margin the new pool does not clear).
    function _pool(F.Kind kind, address a, address b, uint256 units) private returns (bool) {
        (address t0, address t1) = _sorted(a, b);
        uint256 r0 = units * 10 ** _dec(t0);
        uint256 r1 = units * 10 ** _dec(t1);
        address p;
        uint8 kindNo;
        uint24 fee;
        if (kind == F.Kind.V2) {
            MockV2Pair v2 = new MockV2Pair(t0, t1);
            v2.setReserves(uint112(r0), uint112(r1));
            p = address(v2); kindNo = BPC.KIND_V2; fee = 30;
        } else if (kind == F.Kind.V3) {
            MockV3Pool v3 = new MockV3Pool(t0, t1, 3000);
            v3.setState(uint160(BPC.Q96), V3_LIQ);
            p = address(v3); kindNo = BPC.KIND_V3; fee = 3000;
        } else {
            MockSolidlyPair sp = new MockSolidlyPair(t0, t1, false);
            sp.setReserves(uint112(r0), uint112(r1));
            p = address(sp); kindNo = BPC.KIND_SOLIDLY; fee = 0;
        }
        _mint(t0, p, units);
        _mint(t1, p, units);
        try hub.seedPool(p, kindNo, fee, address(0), t0, t1) {
            pools.push(p);
            return true;
        } catch {
            return false;
        }
    }

    function _build(Row memory r) private {
        _stack();
        delete path; delete pools; notBuilt = "";
        taxIn = r.fot == F.Fot.FOT_PULL;
        pathIn = r.decimalsIn == F.Dec.D6 && !taxIn;
        address tIn = _tokenIn(r);
        if (tIn == address(0)) return;
        path.push(tIn);
        uint256 n = r.hops == F.Hops.H1 ? 1 : r.hops == F.Hops.H2 ? 2 : 3;
        for (uint256 i = 1; i <= n; ++i) path.push(address(new MockERC20("T", "T")));

        if (r.inBridge == F.InB.IN_BRIDGE) hub.addBridge(path[0]);
        if (r.midBridge == F.MidB.MID_BRIDGE) for (uint256 i = 1; i < n; ++i) hub.addBridge(path[i]);

        for (uint256 h; h < n; ++h) {
            if (h == 0 && r.pairFull == F.Full.PAIR_FULL) {
                // sixteen dust pools first: the pair is full before the row's pools arrive
                for (uint256 d; d < 16; ++d) {
                    if (!_pool(F.Kind.V2, path[0], path[1], 10)) { notBuilt = "dust pool refused while filling the pair"; return; }
                }
            }
            uint256 legs = r.legs == F.Legs.L1 ? 1 : 2;
            for (uint256 l; l < legs; ++l) {
                if (!_pool(r.kind, path[h], path[h + 1], DEPTH_UNITS)) { notBuilt = "full pair: the Hub refused the row's pool"; return; }
            }
        }
        _mint(path[0], user, AMOUNT_UNITS * 10);
        vm.startPrank(user);
        IERC20Min(path[0]).approve(address(router), type(uint256).max);
        IERC20Min(path[0]).approve(address(permit2), type(uint256).max);
        vm.stopPrank();
        if (r.control == F.Ctl.RENOUNCED) hub.renounceControl();
    }

    // ------------------------------------------------------------------ route

    function _leg(address pool, F.Kind kind, address tIn, address tOut, uint256 amt)
        private view returns (Leg memory lg, uint256 out)
    {
        (address t0,) = _sorted(tIn, tOut);
        bool zfo = tIn == t0;
        if (kind == F.Kind.V2) {
            (uint112 r0, uint112 r1,) = MockV2Pair(pool).getReserves();
            out = BPC.outV2(amt, zfo ? r0 : r1, zfo ? r1 : r0, 30);
            lg = Leg({pool: pool, hooks: address(0), kind: BPC.KIND_V2, fee: 30, tickSpacing: 0,
                      zeroForOne: zfo, stable: false, amountIn: amt, expectedOut: out, auxId: bytes32(0)});
        } else if (kind == F.Kind.V3) {
            out = BPC.outV3(amt, uint160(BPC.Q96), V3_LIQ, 3000, zfo, 0);
            lg = Leg({pool: pool, hooks: address(0), kind: BPC.KIND_V3, fee: 3000, tickSpacing: 60,
                      zeroForOne: zfo, stable: false, amountIn: amt, expectedOut: out, auxId: bytes32(0)});
        } else {
            out = MockSolidlyPair(pool).getAmountOut(amt, tIn);
            lg = Leg({pool: pool, hooks: address(0), kind: BPC.KIND_SOLIDLY, fee: 0, tickSpacing: 0,
                      zeroForOne: zfo, stable: false, amountIn: amt, expectedOut: out, auxId: bytes32(0)});
        }
    }

    /// A one-leg-per-hop route through the first pool seeded on each pair, quoted by the
    /// pools' own maths. Used when the Solver has no bridged path to build.
    function _handRoute(Row memory r, uint256 amountIn) private view returns (Route memory route) {
        uint256 n = path.length - 1;
        uint256 legsPerHop = r.legs == F.Legs.L1 ? 1 : 2;
        uint256 dust = r.pairFull == F.Full.PAIR_FULL ? 16 : 0;
        Hop[] memory hops = new Hop[](n);
        uint256 amt = amountIn;
        for (uint256 h; h < n; ++h) {
            uint256 idx = (h == 0 ? dust : dust + legsPerHop * h);   // first row pool of hop h
            if (h > 0) idx = dust + legsPerHop * h;
            Leg[] memory legs = new Leg[](1);
            (Leg memory lg, uint256 out) = _leg(pools[idx], r.kind, path[h], path[h + 1], amt);
            legs[0] = lg;
            hops[h] = Hop({tokenIn: path[h], tokenOut: path[h + 1], amountIn: amt, expectedOut: out, legs: legs});
            amt = out;
        }
        route = Route({hops: hops, totalOut: amt, singleOut: amt, singleOutFloor: 0, expectedImpactBps: 0,
                       confidenceWad: 0, estGas: 0, hasSurplus: false, isV4Bundle: false});
    }

    function _route(Row memory r, uint256 amountIn) private view returns (Route memory route, bool fromSolver) {
        try solver.findBestRoutePlan(path[0], path[path.length - 1], amountIn) returns (RoutePlan memory plan) {
            if (plan.best.hops.length > 0) return (plan.best, true);
        } catch {}
        return (_handRoute(r, amountIn), false);
    }

    // ------------------------------------------------------------------ run

    function _run(uint256 id, Row memory r) internal {
        _build(r);
        if (bytes(notBuilt).length != 0) {
            console2.log("ROW", id, "NOT_CONSTRUCTIBLE", notBuilt);
            return;
        }
        address tIn = path[0];
        address tOut = path[path.length - 1];
        uint256 amountIn = AMOUNT_UNITS * 10 ** _dec(tIn);
        uint256 before = IERC20Min(tOut).balanceOf(user);
        uint256 deadline = block.timestamp + 1;

        (Route memory route, bool fromSolver) = _route(r, amountIn);
        bool ok; bytes memory err; uint256 got;
        vm.recordLogs();
        vm.prank(user);
        if (r.door == F.Door.EXACT_IN) {
            (ok, err) = address(router).call(abi.encodeCall(router.swapExactIn, (route, amountIn, 1, user, deadline)));
        } else if (r.door == F.Door.BEST) {
            (ok, err) = address(router).call(abi.encodeCall(router.swapBestExactIn, (tIn, tOut, amountIn, 1, user, deadline)));
        } else {
            IPermit2.PermitTransferFrom memory permit = IPermit2.PermitTransferFrom({
                permitted: IPermit2.TokenPermissions({token: tIn, amount: amountIn}), nonce: 0, deadline: deadline
            });
            (ok, err) = address(router).call(abi.encodeCall(router.swapExactInWithPermit2, (route, amountIn, 1, user, deadline, permit, "")));
        }

        if (ok) {
            got = abi.decode(err, (uint256));
            uint256 delta = IERC20Min(tOut).balanceOf(user) - before;
            assertEq(got, delta, "delivered must equal the recipient's balance delta");
            assertGt(got, 0, "a settled swap delivers something");
            // THE FLOOR THE ROUTER ENFORCED is the one it emits in ExecutionProof. A token
            // that taxes transfers is measured at the pull and the floor is re-priced by the
            // measured ratio (FoT routed where natural), so the attested nominal floor is the
            // right comparison only when nothing was taxed; the emitted floor always is.
            (uint256 floorUsed, bool proved) = _floorUsed(vm.getRecordedLogs());
            assertTrue(proved, "a settled swap emits its ExecutionProof");
            assertGe(got, floorUsed, "delivered at least the floor the Router enforced");
            if (fromSolver && r.fot == F.Fot.FOT_NONE) {
                // WHERE THE FEE IS TAKEN DECIDES THE FLOOR'S FRAME. Both producers apply
                // `ironFloorBps` to their own in-frame quote; the frames differ by the fee. Fee on the OUTPUT (a single
                // hop into a bridge): the Router's in-frame quote is the Solver's, and the
                // enforced floor is the attested one exactly. Fee on the INPUT: the legs receive
                // the net amount, the Router re-derives its floor on that, and the result sits in
                // [attested x (1 - fee), attested] - the lower edge by the fee, the upper by the
                // curve's convexity (less input, a slightly better rate). Both edges are exact.
                bool feeOnOut = route.hops.length == 1 && hub.isBridgeToken(tOut);
                if (feeOnOut) {
                    assertEq(floorUsed, route.singleOutFloor, "fee on the output: the enforced floor is the attested floor");
                } else {
                    uint256 lo = BPC.mulDiv(route.singleOutFloor, BPC.BPS - BPC.PROTOCOL_FEE_BPS, BPC.BPS);
                    assertGe(floorUsed, lo, "fee on the input: the enforced floor is at least the attested floor net of the fee");
                    assertLe(floorUsed, route.singleOutFloor, "fee on the input: the enforced floor never exceeds the attested floor");
                }
            }
            for (uint256 i; i < path.length; ++i) {
                assertEq(IERC20Min(path[i]).balanceOf(address(router)), 0, "the Router holds nothing after a swap");
            }
            console2.log("ROW", id, "SETTLED", got);
            return;
        }
        (bool ours, string memory what) = Outcomes.classify(err);
        assertTrue(ours, string.concat("refused without a selector of ours: ", what));
        console2.log("ROW", id, "REFUSED", what);
    }

    bytes32 constant PROOF = keccak256("ExecutionProof(address,address,uint256,uint256,uint256,uint256)");

    /// The third word of the ExecutionProof data: the floor the Router enforced.
    function _floorUsed(Vm.Log[] memory logs) private pure returns (uint256 floorOut, bool found) {
        for (uint256 i; i < logs.length; ++i) {
            if (logs[i].topics[0] == PROOF) {
                (, , floorOut, ) = abi.decode(logs[i].data, (uint256, uint256, uint256, uint256));
                return (floorOut, true);
            }
        }
    }
}
