// SPDX-License-Identifier: BUSL-1.1
pragma solidity 0.8.36;

// GENERATED by .github/scripts/assurance/covering_array.py - do not edit by hand.
// A strength-3 covering array over the regime factors: every 3-tuple of factor values
// appears in at least one row below. Each row is one fixture run through RegimeHarness,
// which either settles inside its floors or is refused with a selector of ours.

import {RegimeHarness, F} from "./RegimeHarness.sol";

contract RegimeCoverageT3Test is RegimeHarness {
    function test_Regime3_00_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(0, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_01_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(1, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_02_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(2, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_03_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(3, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_04_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(4, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_05_V2_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(5, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_06_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(6, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_07_V3_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(7, Row(F.Kind.V3, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_08_V3_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(8, Row(F.Kind.V3, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_09_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(9, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_10_V3_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(10, Row(F.Kind.V3, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_11_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(11, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_12_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(12, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_13_SOLIDLY_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(13, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_14_SOLIDLY_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(14, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_15_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(15, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_16_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(16, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_17_SOLIDLY_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(17, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_18_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(18, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_19_V2_H2_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(19, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_20_V2_H3_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(20, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_21_V3_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(21, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_22_V3_H2_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(22, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_23_V3_H3_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(23, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_24_SOLIDLY_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(24, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_25_SOLIDLY_H2_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(25, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_26_SOLIDLY_H3_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(26, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_27_V2_H1_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(27, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_28_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(28, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_29_V2_H1_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(29, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_30_V2_H2_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(30, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_31_V2_H2_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(31, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_32_V2_H3_L2_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(32, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_33_V2_H3_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(33, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_34_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(34, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_35_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(35, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_36_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(36, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_37_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(37, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_38_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(38, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_39_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(39, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_40_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(40, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_41_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(41, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_42_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(42, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_43_V2_H1_L1_IN_BRIDGE_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(43, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_BRIDGE, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_44_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(44, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_45_V2_H2_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(45, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_46_V2_H3_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(46, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_47_V3_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(47, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_48_V3_H2_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(48, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_49_V3_H3_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(49, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_50_SOLIDLY_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(50, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_51_SOLIDLY_H2_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(51, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_52_SOLIDLY_H3_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(52, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_53_V2_H1_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(53, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_54_V2_H1_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(54, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_55_V2_H2_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(55, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_56_V2_H2_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(56, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_57_V2_H3_L2_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(57, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_58_V2_H3_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(58, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_59_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(59, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_60_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(60, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_61_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(61, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_62_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(62, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_63_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(63, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_64_V2_H1_L1_IN_PLAIN_MID_BRIDGE_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(64, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_BRIDGE, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_65_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(65, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_66_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(66, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_67_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(67, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_68_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(68, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_69_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(69, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_70_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(70, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_71_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(71, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_72_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(72, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_73_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(73, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_74_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(74, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_75_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(75, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_76_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(76, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_77_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(77, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_78_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(78, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_79_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(79, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_80_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(80, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_81_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(81, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_82_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(82, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_83_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(83, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_84_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(84, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_85_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(85, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_86_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(86, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_87_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(87, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_88_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(88, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_89_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(89, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_90_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(90, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_91_V2_H3_L2_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(91, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_92_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(92, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_93_V2_H3_L2_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(93, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_94_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(94, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_95_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(95, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_96_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(96, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_97_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_PULL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(97, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_PULL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_98_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(98, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_99_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(99, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_100_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_ALL_D18_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(100, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_ALL, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_101_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(101, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_102_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(102, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_103_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(103, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_104_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(104, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_105_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(105, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_106_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(106, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_107_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(107, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_108_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(108, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_109_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(109, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_110_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(110, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_111_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(111, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_112_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(112, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_113_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(113, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_114_V2_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(114, Row(F.Kind.V2, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_115_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(115, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_116_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D6_EXACT_IN_LIVE_PAIR_OPEN() public {
        _run(116, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D6, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_117_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(117, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_118_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(118, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_119_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(119, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_120_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(120, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_121_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(121, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_122_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(122, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_123_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(123, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_124_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(124, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_125_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(125, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_126_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(126, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_127_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(127, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_128_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(128, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_129_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(129, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_130_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(130, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_131_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(131, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_132_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(132, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_133_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(133, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_134_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(134, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_135_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(135, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_136_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(136, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_137_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(137, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_138_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(138, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_139_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(139, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_140_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(140, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_141_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(141, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_142_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_BEST_LIVE_PAIR_OPEN() public {
        _run(142, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.BEST, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_143_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(143, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_144_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_PERMIT2_LIVE_PAIR_OPEN() public {
        _run(144, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.PERMIT2, F.Ctl.LIVE, F.Full.PAIR_OPEN));
    }

    function test_Regime3_145_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(145, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_146_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(146, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_147_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(147, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_148_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(148, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_149_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(149, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_150_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(150, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_151_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(151, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_152_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(152, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_153_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(153, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_154_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(154, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_155_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(155, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_156_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_RENOUNCED_PAIR_OPEN() public {
        _run(156, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.RENOUNCED, F.Full.PAIR_OPEN));
    }

    function test_Regime3_157_V2_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(157, Row(F.Kind.V2, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_158_V2_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(158, Row(F.Kind.V2, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_159_V2_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(159, Row(F.Kind.V2, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_160_V3_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(160, Row(F.Kind.V3, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_161_V3_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(161, Row(F.Kind.V3, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_162_V3_H3_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(162, Row(F.Kind.V3, F.Hops.H3, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_163_SOLIDLY_H1_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(163, Row(F.Kind.SOLIDLY, F.Hops.H1, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_164_SOLIDLY_H2_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(164, Row(F.Kind.SOLIDLY, F.Hops.H2, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_165_SOLIDLY_H3_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(165, Row(F.Kind.SOLIDLY, F.Hops.H3, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_166_V2_H1_L2_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(166, Row(F.Kind.V2, F.Hops.H1, F.Legs.L2, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

    function test_Regime3_167_V2_H2_L1_IN_PLAIN_MID_PLAIN_FOT_NONE_D18_EXACT_IN_LIVE_PAIR_FULL() public {
        _run(167, Row(F.Kind.V2, F.Hops.H2, F.Legs.L1, F.InB.IN_PLAIN, F.MidB.MID_PLAIN, F.Fot.FOT_NONE, F.Dec.D18, F.Door.EXACT_IN, F.Ctl.LIVE, F.Full.PAIR_FULL));
    }

}
